### ISSUE TITLE
Version and release tags

### ISSUE THREAD

**Issue by barrydegraaff** [chrisveness/crypto#2]
Hello Chris,

Thanks for your work on this really nice library!

Would it be possible to implement version numbers, or maybe start using `release` tags feature in Github? Having version numbers and a clear difference between released and development versions would be good for the quality of the project.

Thanks,  Barry
https://github.com/Zimbra-Community/pgp-zimlet

**Comment by chrisveness** [comment]
Thank you for your appreciation and confidence in these libraries.

However, I try to make it clear that they are intended for exploring/understanding the algorithms rather than for production use; there are more efficient implementations available, and I can offer no warranty or guarantees (important for cryptographic applications!). Using version numbers and/or release tags could give a false impression as to the suitability of this code for production environments.

For production use, I suggest looking into e.g. [SubtleCrypto](https://developer.mozilla.org/en/docs/Web/API/SubtleCrypto), [Node.js Crypto](https://nodejs.org/api/crypto.html), etc ([Charles Engelke's Blog](http://blog.engelke.com/2014/06/22/symmetric-cryptography-in-the-browser-part-1/) has a decent intro).
